cloud:
  aws:
    credentials:
      access-key: AKIA56SFB3XZZCVI7GOM
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: hruiz17storage

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090