server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOSTNAME}:8091/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-cliente
          uri: lb://servicio-cliente
          predicates:
            - Path=/api/cliente/**
        - id: servicio-foto
          uri: lb://servicio-foto
          predicates:
            - Path=/file/**