drop table if exists ciudad CASCADE;
drop table if exists cliente CASCADE;
drop table if exists tipo_documento CASCADE;
create table ciudad (id bigint generated by default as identity, nombre varchar(255) not null, primary key (id));
create table cliente (id bigint generated by default as identity, apellidos varchar(255) not null, edad integer not null, id_ciudad_nacimiento bigint not null, id_foto varchar(255), id_tipo_documento bigint not null, nombres varchar(255) not null, numero_documento bigint not null, primary key (id));
create table tipo_documento (id bigint generated by default as identity, nombre varchar(255) not null, primary key (id));
alter table cliente add constraint identificacion unique (id_tipo_documento, numero_documento);
alter table cliente add constraint FKaie5st6uf7q67pgf08i6998v8 foreign key (id_ciudad_nacimiento) references ciudad;
alter table cliente add constraint FKt7kpxymxqw54nlc2q667f1bf foreign key (id_tipo_documento) references tipo_documento;

insert into tipo_documento (ID, NOMBRE) values(1, 'CEDULA');
insert into tipo_documento (ID, NOMBRE) values(2, 'TARJETA IDENTIDAD');
insert into tipo_documento (ID, NOMBRE) values(3, 'PASAPORTE');

insert into ciudad (ID, NOMBRE) values(1, 'MEDELLIN');
insert into ciudad (ID, NOMBRE) values(2, 'BOGOTA');
insert into ciudad (ID, NOMBRE) values(3, 'CALI');
insert into ciudad (ID, NOMBRE) values(4, 'BARRANQUILLA');
insert into ciudad (ID, NOMBRE) values(5, 'CUCUTA');
insert into ciudad (ID, NOMBRE) values(6, 'BUCARAMANGA');
insert into ciudad (ID, NOMBRE) values(7, 'MANIZALES');
insert into ciudad (ID, NOMBRE) values(8, 'PEREIRA');
insert into ciudad (ID, NOMBRE) values(9, 'CARTAGENA');
insert into ciudad (ID, NOMBRE) values(10, 'VILLAVICENCIO');
insert into ciudad (ID, NOMBRE) values(11, 'IBAGUE');
insert into ciudad (ID, NOMBRE) values(12, 'SANTA MARTA');
insert into ciudad (ID, NOMBRE) values(13, 'MONTERIA');
insert into ciudad (ID, NOMBRE) values(14, 'PASTO');
insert into ciudad (ID, NOMBRE) values(15, 'NEIVA');
insert into ciudad (ID, NOMBRE) values(16, 'ARMENIA');

insert into cliente (ID, NOMBRES, APELLIDOS, ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, EDAD, ID_CIUDAD_NACIMIENTO,ID_FOTO)values(1, 'MARIA CLAUDIA','MONTOYA PEREZ',1,94536214,24,1,NULL);
